create table hot_topics (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade,
  search_keyword text,
  views_count integer not null default 0,
  reactions_count integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint hot_topics_post_id_unique unique (post_id),
  constraint hot_topics_search_keyword_unique unique (search_keyword)
);

create or replace function update_hot_topics ()
returns trigger as $$
begin
  if new.view_count >= 100 then
    insert into hot_topics (post_id, views_count, reactions_count)
    values (new.id, new.view_count, new.likes_count)
    on conflict (post_id)
    do update set
      views_count = new.view_count,
      reactions_count = new.likes_count,
      updated_at = now();
  end if;
  return new;
end;
$$ language plpgsql;

create trigger update_hot_topics_trigger
after update of view_count on posts
for each row
execute function update_hot_topics();
