create table search_trends (
  id bigint generated by default as identity primary key,
  keyword text not null,
  search_count integer not null default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint search_trends_keyword_unique unique (keyword)
);

create or replace function track_search (search_keyword text)
returns void as $$
begin
  insert into search_trends (keyword)
  values (search_keyword)
  on conflict (keyword)
  do update set
    search_count = search_trends.search_count + 1,
    updated_at = now();
end;
$$ language plpgsql;
